# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 329c4edfa9732d644b89228cf6bd3699cc9674790cf0739ed82c65fb1644139b68d9c5f9442146e2951b8384f26e3c8226d922fc041d5d006c6402041c68e5bf

test:
  secret_key_base: 5615988234b099998717bbcbb2d47dfde8807f566babbfec7bf77bb4b30f0b69e993ed1d31c13530ab39701878b2d27fd92fb1b87642f6b7122b8514c9d748ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
